server:
  port: 9999
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1111/eureka/
spring:
  application:
    name: zuul-service
#zuul url映射配置
zuul:
  routes:
    api-user:
      path: /api-user/**
      serviceId: user-service
