server:
  port: 1113
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1111/eureka/
    eureka-connection-idle-timeout-seconds: 40
    eureka-server-read-timeout-seconds: 20
    eureka-service-url-poll-interval-seconds: 20
spring:
  profiles:
    active: dev
  application:
    name: computer-service
  zipkin:
    base-url: http://localhost:9111
# THYMELEAF (ThymeleafAutoConfiguration)
#开启模板缓存（默认值：true）
#  thymeleaf:
#    cache: true
##Check that the template exists before rendering it.
#    check-template: true
##检查模板位置是否正确（默认值:true）
#    check-template-location: true
##Content-Type的值（默认值：text/html）
#    content-type: text/html
##开启MVC Thymeleaf视图解析（默认值：true）
#    enabled: true
##模板编码
#    encoding: UTF-8
##要被排除在解析之外的视图名称列表，用逗号分隔
#    excluded-view-names:
##要运用于模板之上的模板模式。另见StandardTemplate-ModeHandlers(默认值：HTML5)
#    mode: HTML5
##在构建URL时添加到视图名称前的前缀（默认值：classpath:/templates/）
#    prefix: classpath:/templates/
##在构建URL时添加到视图名称后的后缀（默认值：.html）
#    suffix: .html
#Thymeleaf模板解析器在解析器链中的顺序。默认情况下，它排第一位。顺序从1开始，只有在定义了额外的TemplateResolver Bean时才需要设置这个属性。
#    template-resolver-order:
#可解析的视图名称列表，用逗号分隔
#    view-names:

#redis配置
  redis:
#  数据库索引
    database: 0
#    服务器地址
    host: 127.0.0.1
#    服务器连接端口
    port: 6379
#    链接密码
    password:
#    链接池
    pool:
#    最大连接数（负值表示没有限制）
      max-active: 8
#      最大阻塞等待时间（负值表示没有限制）
      max-wait: 1
#      最大空闲链接
      max-idle: 8
#      最小空闲链接
      min-idle: 0
#    链接超时时间（毫秒）
    timeout: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml