server:
  port: 1115
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhuzhengping911/Spring-Cloud/
          search-paths: config/config-repo
          username: zhuzhengping911
          password: while(1)me&&XW
      enabled: true
#  jmx:
#    default_domain: cloud.config.server
#  profiles:
#    active: dev
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1111/eureka/