server:
  port: 7001
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: http://github.com/zhuzhengping911/Spring-Cloud/
          search-paths: config/config-repo
          username: 
          password:
  profiles:
    active: native