server:
  port: 7001
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhuzhengping911/Spring-Cloud/
          search-paths: config/config-repo
          username:
          password:
#  profiles:
#    active: native
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1111/eureka/